name: Build and Run OpenAiCodeReview By Main Maven Jar

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    # 指定运行环境为最新的 Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # 设置检出深度为 2，通常用于比较两次提交之间的差异
          fetch-depth: 2

      # 步骤 2: 设置 JDK 11 环境
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          # 使用 Adoptium 的 JDK 分发
          distribution: 'adopt'
          # 设置 JDK 版本为 11
          java-version: '11'

      # 步骤 3: 创建存放依赖库的目录
      - name: Create libs directory
        run: mkdir -p ./libs

      # 步骤 4: 下载 openai-code-review-sdk JAR 文件
      - name: Download openai-code-review-sdk JAR
        run: curl -L -o ./libs/openai-code-review-sdk-1.0.jar https://github.com/18826377472/openai-code-review-log/releases/download/v1.0/openai-code-review-sdk-1.0.jar

      # 步骤 5: 获取仓库名称
      - name: Get repository name
        id: repo-name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      # 步骤 6: 获取分支名称
      - name: Get branch name
        id: branch-name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      # 步骤 7: 获取提交作者
      - name: Get commit author
        id: commit-author
        run: echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')" >> $GITHUB_ENV

      # 步骤 8: 获取提交信息
      - name: Get commit message
        id: commit-message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      # 步骤 9: 打印仓库名称、分支名称、提交作者和提交信息
      - name: Print repository, branch name, commit author, and commit message
        run: |          
          echo "Repository name is ${{ env.REPO_NAME }}"
          echo "Branch name is ${{ env.BRANCH_NAME }}"
          echo "Commit author is ${{ env.COMMIT_AUTHOR }}"
          echo "Commit message is ${{ env.COMMIT_MESSAGE }}"      

      # 步骤 10: 运行代码审查工具
      - name: Run Code Review
        run: java -jar ./libs/openai-code-review-sdk-1.0.jar
        # 设置环境变量
        env:
          # Github 相关配置
          GITHUB_REVIEW_LOG_URI: ${{ secrets.CODE_REVIEW_LOG_URI }}
          GITHUB_TOKEN: ${{ secrets.CODE_TOKEN }}
          COMMIT_PROJECT: ${{ env.REPO_NAME }}
          COMMIT_BRANCH: ${{ env.BRANCH_NAME }}
          COMMIT_AUTHOR: ${{ env.COMMIT_AUTHOR }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
          # 微信相关配置
          WEIXIN_APPID: ${{ secrets.WEIXIN_APPID }}
          WEIXIN_SECRET: ${{ secrets.WEIXIN_SECRET }}
          WEIXIN_TOUSER: ${{ secrets.WEIXIN_TOUSER }}
          WEIXIN_TEMPLATE_ID: ${{ secrets.WEIXIN_TEMPLATE_ID }}
          # OpenAi - ChatGLM 相关配置
          CHATGLM_APIHOST: ${{ secrets.CHATGLM_APIHOST }}
          CHATGLM_APIKEYSECRET: ${{ secrets.CHATGLM_APIKEYSECRET }}